# Generated by Django 4.1.7 on 2023-03-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AddField(
            model_name='member',
            name='brandname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='member',
            name='productname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='reviews',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='reviewvotes',
            field=models.IntegerField(default=0),
        ),
    ]
